# Render.com Configuration for News Bot
# This is a WORKER service, not a web application

services:
  - type: worker
    name: news-bot-worker
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python start.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
    autoDeploy: true
    
# Important: This is NOT a web service
# It's a background worker that runs the Telegram bot